---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-academic-boilerplate-lumen
  labels:
    svc: svc-academic-boilerplate-lumen
    tier: backend
  namespace: academic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: svc-academic-boilerplate-lumen
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        svc: svc-academic-boilerplate-lumen
        tier: backend
    spec:
      imagePullSecrets:
        - name: gcr-uii-key
      containers:
        - name: svc-academic-boilerplate-lumen
          image: asia.gcr.io/uii-cloud-project/academic/backend/svc-academic-boilerplate-lumen:dev
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              memory: 500Mi
          env:
            - name: APP_DEBUG
              value: "true"
            - name: DB_HOST
              value: "dbdev.bsi.io"
            - name: DB_PORT
              value: "6033"
            - name: DB_USERNAME
              value: "dev"
            - name: DB_PASSWORD
              value: "bismillah"
            - name: WORKER_PROCESSES
              value: "auto"
            - name: WORKER_CONNECTIONS
              value: "768"
            - name: PM_MAX_CHILDREN
              value: "40"
            - name: PM_START_SERVER
              value: "10"
            - name: PM_MIN_SPARE_SERVER
              value: "10"
            - name: PM_MAX_SPARE_SERVER
              value: "20"
            - name: MAX_EXECUTION_TIME
              value: "60"
            - name: PHP_MEMORY_LIMIT
              value: "128M"
            - name: PHP_OPCACHE_MEMORY
              value: "16"
          ports:
            - name: http-api
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-academic-boilerplate-lumen
  labels:
    svc: svc-academic-boilerplate-lumen
    tier: backend
  namespace: academic-dev
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  svc-academic-boilerplate-lumen-mapping
      prefix: /v1/boilerplate
      rewrite: /public/api/v1
      service: svc-academic-boilerplate-lumen.academic-dev
      timeout_ms: 180000
spec:
  selector:
    svc: svc-academic-boilerplate-lumen
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
